const ACTION_TYPES = {
    ADD_CONTACT: 'ADD_CONTACT',
    DELETE_CONTACT: 'DELETE_CONTACT',
    GET_CONTACTS: 'GET_CONTACTS',
    SELECT_CONTACT: 'SELECT_CONTACT',
    CREATE_NEW_CONTACT: 'CREATE_NEW_CONTACT',
    UPDATE_CONTACT: 'UPDATE_CONTACT',
}

export default ACTION_TYPES;